using System.ComponentModel.DataAnnotations;

namespace VTE.Api.Dtos;

public record VehicleListItem(
    long Id,
    byte CompanyId,
    string Vin,
    string? Plate,
    int? ModelId,
    string? Model,
    string? Maker,
    int? BodyTypeId,
    string? BodyType,
    short? CategoryId,
    string? Category,
    short? PrimaryColorId,
    string? PrimaryColor,
    float? EnginePowerKw,
    float? EngineWorkingCapacityCc,
    string? OwnerName,
    string? OwnerEmbg,
    bool Active,
    // Each row in the list corresponds to one ClientVehicleRelation. RelationId is
    // the table's dataKey; multiple rows can share the same vehicle Id when a
    // vehicle has more than one active client (owner + authorized, history, …).
    long RelationId,
    byte RelationTypeId,
    string? RelationTypeName
);

public record VehicleReadDto(
    long Id,
    byte CompanyId,
    string Vin,
    string? EngineNumber,
    string? Plate,
    short? CategoryId,
    int? BodyTypeId,
    int? ModelId,
    short? PrimaryColorId,
    short? SecondaryColorId,
    short? MadeCountryId,
    byte? FuelId,
    byte? SecondFuelId,
    int? EngineTypeId,
    byte? EcoProgramId,
    byte? PaymentCategoryId,
    float? EnginePowerKw,
    float? EngineWorkingCapacityCc,
    int? MaxRpm,
    float? MaxSpeedKmh,
    bool? HasLpg,
    float? LengthMm, float? WidthMm, float? HeightMm,
    float? EmptyWeightKg, float? MaxAllowedWeightKg,
    float? MaxLegalTotalMassKg, float? MaxConstructiveTotalMassKg,
    string? TrailerMassWithBrakesKg, string? TrailerMassWithoutBrakesKg,
    int? AxleCount, int? WheelCount, int? AxleLoad1Kg, int? AxleLoad2Kg,
    short? Seats, short? StandingSeats,
    float? Co2GKm, float? NoiseStaticDb, float? NoiseMovingDb,
    string? TypeText, string? ModelVariant, string? ApprovalMark,
    string? Note, bool Active, DateTime CreatedAt
);

public record VehicleWriteDto(
    [Required, MaxLength(40)] string Vin,
    [MaxLength(40)] string? EngineNumber,
    [MaxLength(20)] string? Plate,
    short? CategoryId,
    int? BodyTypeId,
    int? ModelId,
    short? PrimaryColorId,
    short? SecondaryColorId,
    short? MadeCountryId,
    byte? FuelId,
    byte? SecondFuelId,
    int? EngineTypeId,
    byte? EcoProgramId,
    byte? PaymentCategoryId,
    float? EnginePowerKw,
    float? EngineWorkingCapacityCc,
    int? MaxRpm,
    float? MaxSpeedKmh,
    bool? HasLpg,
    float? LengthMm, float? WidthMm, float? HeightMm,
    float? EmptyWeightKg, float? MaxAllowedWeightKg,
    float? MaxLegalTotalMassKg, float? MaxConstructiveTotalMassKg,
    [MaxLength(40)] string? TrailerMassWithBrakesKg,
    [MaxLength(40)] string? TrailerMassWithoutBrakesKg,
    int? AxleCount, int? WheelCount, int? AxleLoad1Kg, int? AxleLoad2Kg,
    short? Seats, short? StandingSeats,
    float? Co2GKm, float? NoiseStaticDb, float? NoiseMovingDb,
    [MaxLength(300)] string? TypeText,
    [MaxLength(400)] string? ModelVariant,
    [MaxLength(100)] string? ApprovalMark,
    [MaxLength(1000)] string? Note,
    bool? Active,
    /// <summary>Admin-only override; operators always write to their own tenant.</summary>
    byte? CompanyId = null
);
