'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18047
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class VehicleFieldsResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VTE.Library.VehicleFieldsResource", GetType(VehicleFieldsResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blackening.
        '''</summary>
        Friend Shared ReadOnly Property Blackening() As String
            Get
                Return ResourceManager.GetString("Blackening", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Капацитет на резервоар.
        '''</summary>
        Friend Shared ReadOnly Property CapacityFuelTank() As String
            Get
                Return ResourceManager.GetString("CapacityFuelTank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CO.
        '''</summary>
        Friend Shared ReadOnly Property CO() As String
            Get
                Return ResourceManager.GetString("CO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CO2.
        '''</summary>
        Friend Shared ReadOnly Property CO2() As String
            Get
                Return ResourceManager.GetString("CO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Код на боја.
        '''</summary>
        Friend Shared ReadOnly Property ColorCode() As String
            Get
                Return ResourceManager.GetString("ColorCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сопсвена маса.
        '''</summary>
        Friend Shared ReadOnly Property EmptyWaight() As String
            Get
                Return ResourceManager.GetString("EmptyWaight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на мотор.
        '''</summary>
        Friend Shared ReadOnly Property EngineNumber() As String
            Get
                Return ResourceManager.GetString("EngineNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кањажа.
        '''</summary>
        Friend Shared ReadOnly Property EnginePower() As String
            Get
                Return ResourceManager.GetString("EnginePower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Силина(kW).
        '''</summary>
        Friend Shared ReadOnly Property EnginePowerOutPut() As String
            Get
                Return ResourceManager.GetString("EnginePowerOutPut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на вртежи.
        '''</summary>
        Friend Shared ReadOnly Property EngineTorque() As String
            Get
                Return ResourceManager.GetString("EngineTorque", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на врежи под гас.
        '''</summary>
        Friend Shared ReadOnly Property EngineTorqueUnderGass() As String
            Get
                Return ResourceManager.GetString("EngineTorqueUnderGass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Работна зафатнина.
        '''</summary>
        Friend Shared ReadOnly Property EngineWorkingCapacity() As String
            Get
                Return ResourceManager.GetString("EngineWorkingCapacity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ForPrivateTransportNotPublic.
        '''</summary>
        Friend Shared ReadOnly Property ForPrivateTransportNotPublic() As String
            Get
                Return ResourceManager.GetString("ForPrivateTransportNotPublic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Порошувачка на гориво.
        '''</summary>
        Friend Shared ReadOnly Property FuelConsumption() As String
            Get
                Return ResourceManager.GetString("FuelConsumption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HC.
        '''</summary>
        Friend Shared ReadOnly Property HC() As String
            Get
                Return ResourceManager.GetString("HC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HCNOx.
        '''</summary>
        Friend Shared ReadOnly Property HCNOx() As String
            Get
                Return ResourceManager.GetString("HCNOx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на хологациски сертификат.
        '''</summary>
        Friend Shared ReadOnly Property HologationSertificateNumber() As String
            Get
                Return ResourceManager.GetString("HologationSertificateNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кука.
        '''</summary>
        Friend Shared ReadOnly Property Hook() As String
            Get
                Return ResourceManager.GetString("Hook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кочници.
        '''</summary>
        Friend Shared ReadOnly Property IdBreakes() As String
            Get
                Return ResourceManager.GetString("IdBreakes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Мотор еко програм.
        '''</summary>
        Friend Shared ReadOnly Property IdEngineEcoProgram() As String
            Get
                Return ResourceManager.GetString("IdEngineEcoProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Гориво.
        '''</summary>
        Friend Shared ReadOnly Property IdEnginePowerSource() As String
            Get
                Return ResourceManager.GetString("IdEnginePowerSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Дополнително гориво.
        '''</summary>
        Friend Shared ReadOnly Property IdEngineSecondPowerSource() As String
            Get
                Return ResourceManager.GetString("IdEngineSecondPowerSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Тип на мотор.
        '''</summary>
        Friend Shared ReadOnly Property IdEngineType() As String
            Get
                Return ResourceManager.GetString("IdEngineType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Менувач.
        '''</summary>
        Friend Shared ReadOnly Property IdGearBox() As String
            Get
                Return ResourceManager.GetString("IdGearBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Земја на производство.
        '''</summary>
        Friend Shared ReadOnly Property IdMadeCountry() As String
            Get
                Return ResourceManager.GetString("IdMadeCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Боја.
        '''</summary>
        Friend Shared ReadOnly Property IdPrimaryColor() As String
            Get
                Return ResourceManager.GetString("IdPrimaryColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Дополнителна боја.
        '''</summary>
        Friend Shared ReadOnly Property IdSecondaryColor() As String
            Get
                Return ResourceManager.GetString("IdSecondaryColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IdSupporting.
        '''</summary>
        Friend Shared ReadOnly Property IdSupporting() As String
            Get
                Return ResourceManager.GetString("IdSupporting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Тип на каросерија.
        '''</summary>
        Friend Shared ReadOnly Property IdVehicleBodyType() As String
            Get
                Return ResourceManager.GetString("IdVehicleBodyType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Категорија на возило.
        '''</summary>
        Friend Shared ReadOnly Property IdVehicleCategories() As String
            Get
                Return ResourceManager.GetString("IdVehicleCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Модел.
        '''</summary>
        Friend Shared ReadOnly Property IdVehicleModel() As String
            Get
                Return ResourceManager.GetString("IdVehicleModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Намена.
        '''</summary>
        Friend Shared ReadOnly Property IdVehicleUse() As String
            Get
                Return ResourceManager.GetString("IdVehicleUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsSocialNotPrivate.
        '''</summary>
        Friend Shared ReadOnly Property IsSocialNotPrivate() As String
            Get
                Return ResourceManager.GetString("IsSocialNotPrivate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Произведено.
        '''</summary>
        Friend Shared ReadOnly Property MakeDate() As String
            Get
                Return ResourceManager.GetString("MakeDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Носивост.
        '''</summary>
        Friend Shared ReadOnly Property MaximunAllowedWaight() As String
            Get
                Return ResourceManager.GetString("MaximunAllowedWaight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Бука при движење.
        '''</summary>
        Friend Shared ReadOnly Property NoiseMovment() As String
            Get
                Return ResourceManager.GetString("NoiseMovment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Бука при мирување.
        '''</summary>
        Friend Shared ReadOnly Property NoiseStatic() As String
            Get
                Return ResourceManager.GetString("NoiseStatic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Заблешка.
        '''</summary>
        Friend Shared ReadOnly Property Note() As String
            Get
                Return ResourceManager.GetString("Note", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NOx.
        '''</summary>
        Friend Shared ReadOnly Property NOx() As String
            Get
                Return ResourceManager.GetString("NOx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на оски.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfAxis() As String
            Get
                Return ResourceManager.GetString("NumberOfAxis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на врати.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfDoors() As String
            Get
                Return ResourceManager.GetString("NumberOfDoors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на лежечки места.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfLieingSeats() As String
            Get
                Return ResourceManager.GetString("NumberOfLieingSeats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на погонски тркала.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfPropulsionWheels() As String
            Get
                Return ResourceManager.GetString("NumberOfPropulsionWheels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на седечки места.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfSeats() As String
            Get
                Return ResourceManager.GetString("NumberOfSeats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на стоечки места.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfStandingSeats() As String
            Get
                Return ResourceManager.GetString("NumberOfStandingSeats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на тркала.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfWheels() As String
            Get
                Return ResourceManager.GetString("NumberOfWheels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pinpoints.
        '''</summary>
        Friend Shared ReadOnly Property Pinpoints() As String
            Get
                Return ResourceManager.GetString("Pinpoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на погонски оски.
        '''</summary>
        Friend Shared ReadOnly Property PropulsionAxis() As String
            Get
                Return ResourceManager.GetString("PropulsionAxis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Број на шасија.
        '''</summary>
        Friend Shared ReadOnly Property ShellNumber() As String
            Get
                Return ResourceManager.GetString("ShellNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suffocation.
        '''</summary>
        Friend Shared ReadOnly Property Suffocation() As String
            Get
                Return ResourceManager.GetString("Suffocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Тежина на приколка со кочници.
        '''</summary>
        Friend Shared ReadOnly Property TrailerWaightWithBreak() As String
            Get
                Return ResourceManager.GetString("TrailerWaightWithBreak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Тежина на приколка без кочници.
        '''</summary>
        Friend Shared ReadOnly Property TrailerWaightWithoutBreak() As String
            Get
                Return ResourceManager.GetString("TrailerWaightWithoutBreak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Висна на возило.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSizeHight() As String
            Get
                Return ResourceManager.GetString("VehicleSizeHight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Должина на возило.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSizeLength() As String
            Get
                Return ResourceManager.GetString("VehicleSizeLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ширина на возило.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSizeWidth() As String
            Get
                Return ResourceManager.GetString("VehicleSizeWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Вертикално оптоварување на седлото.
        '''</summary>
        Friend Shared ReadOnly Property VerticalBurdenOnTheSeat() As String
            Get
                Return ResourceManager.GetString("VerticalBurdenOnTheSeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Вертикално оптоварување на седлото (забелешка).
        '''</summary>
        Friend Shared ReadOnly Property VerticalBurdenOnTheSeatNote() As String
            Get
                Return ResourceManager.GetString("VerticalBurdenOnTheSeatNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Витло.
        '''</summary>
        Friend Shared ReadOnly Property Vitlo() As String
            Get
                Return ResourceManager.GetString("Vitlo", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
