'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18047
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Документот е стониран.
        '''</summary>
        Friend ReadOnly Property DocIsStorno() As String
            Get
                Return ResourceManager.GetString("DocIsStorno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Заврши тест периодот.
        '''</summary>
        Friend ReadOnly Property EndTest() As String
            Get
                Return ResourceManager.GetString("EndTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Погрешно име или лозинка.
        '''</summary>
        Friend ReadOnly Property ErrorPass() As String
            Get
                Return ResourceManager.GetString("ErrorPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property exitNote() As String
            Get
                Return ResourceManager.GetString("exitNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Фискална сметка.
        '''</summary>
        Friend ReadOnly Property Fiscal() As String
            Get
                Return ResourceManager.GetString("Fiscal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GresenBr.
        '''</summary>
        Friend ReadOnly Property GresenBr() As String
            Get
                Return ResourceManager.GetString("GresenBr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GreskaNuliranje.
        '''</summary>
        Friend ReadOnly Property GreskaNuliranje() As String
            Get
                Return ResourceManager.GetString("GreskaNuliranje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Неисправности.
        '''</summary>
        Friend ReadOnly Property IncorectParts() As String
            Get
                Return ResourceManager.GetString("IncorectParts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Информација.
        '''</summary>
        Friend ReadOnly Property Information() As String
            Get
                Return ResourceManager.GetString("Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have made some changes, do you want to save them?.
        '''</summary>
        Friend ReadOnly Property izmeniZacuvaj() As String
            Get
                Return ResourceManager.GetString("izmeniZacuvaj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of birth:.
        '''</summary>
        Friend ReadOnly Property layoutCustomerDateOfBirth() As String
            Get
                Return ResourceManager.GetString("layoutCustomerDateOfBirth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of company&apos;s registration:.
        '''</summary>
        Friend ReadOnly Property layoutCustomerDateOfBirthCompany() As String
            Get
                Return ResourceManager.GetString("layoutCustomerDateOfBirthCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading data ....
        '''</summary>
        Friend ReadOnly Property LoadingData() As String
            Get
                Return ResourceManager.GetString("LoadingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend ReadOnly Property loginStatusLogin() As String
            Get
                Return ResourceManager.GetString("loginStatusLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logout.
        '''</summary>
        Friend ReadOnly Property loginStatusLogout() As String
            Get
                Return ResourceManager.GetString("loginStatusLogout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MBNoDuplicates.
        '''</summary>
        Friend ReadOnly Property MBNoDuplicates() As String
            Get
                Return ResourceManager.GetString("MBNoDuplicates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Min5.
        '''</summary>
        Friend ReadOnly Property Min5() As String
            Get
                Return ResourceManager.GetString("Min5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Min7.
        '''</summary>
        Friend ReadOnly Property Min7() As String
            Get
                Return ResourceManager.GetString("Min7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart the program for complete change of the culture.
        '''</summary>
        Friend ReadOnly Property msgRestartTheProgram() As String
            Get
                Return ResourceManager.GetString("msgRestartTheProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property Nema() As String
            Get
                Return ResourceManager.GetString("Nema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No user is loged in.
        '''</summary>
        Friend ReadOnly Property NeNajaven() As String
            Get
                Return ResourceManager.GetString("NeNajaven", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nePostoi.
        '''</summary>
        Friend ReadOnly Property nePostoi() As String
            Get
                Return ResourceManager.GetString("nePostoi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Немате дозвола да го запамтите објектот, дали сакате да излезете.
        '''</summary>
        Friend ReadOnly Property NoPermisionExit() As String
            Get
                Return ResourceManager.GetString("NoPermisionExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to За документот не се дозволени рати.
        '''</summary>
        Friend ReadOnly Property PartialNot() As String
            Get
                Return ResourceManager.GetString("PartialNot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Печатење.
        '''</summary>
        Friend ReadOnly Property Pecatenje() As String
            Get
                Return ResourceManager.GetString("Pecatenje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Печати договор со рати.
        '''</summary>
        Friend ReadOnly Property PrintDogRata() As String
            Get
                Return ResourceManager.GetString("PrintDogRata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Проблем РС.
        '''</summary>
        Friend ReadOnly Property ProblemPC() As String
            Get
                Return ResourceManager.GetString("ProblemPC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Проверувам....
        '''</summary>
        Friend ReadOnly Property Proveruva() As String
            Get
                Return ResourceManager.GetString("Proveruva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Измени рати.
        '''</summary>
        Friend ReadOnly Property RatiIzmeni() As String
            Get
                Return ResourceManager.GetString("RatiIzmeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сторнирање.
        '''</summary>
        Friend ReadOnly Property Storno() As String
            Get
                Return ResourceManager.GetString("Storno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saveing....
        '''</summary>
        Friend ReadOnly Property textSaveing() As String
            Get
                Return ResourceManager.GetString("textSaveing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading....
        '''</summary>
        Friend ReadOnly Property txtLoading() As String
            Get
                Return ResourceManager.GetString("txtLoading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UspesnoNuliranjNa.
        '''</summary>
        Friend ReadOnly Property UspesnoNuliranjNa() As String
            Get
                Return ResourceManager.GetString("UspesnoNuliranjNa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AttachmentTypes.
        '''</summary>
        Friend ReadOnly Property uxAttachmentTypes() As String
            Get
                Return ResourceManager.GetString("uxAttachmentTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brakes.
        '''</summary>
        Friend ReadOnly Property uxBrakes() As String
            Get
                Return ResourceManager.GetString("uxBrakes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business types.
        '''</summary>
        Friend ReadOnly Property uxBusinessTypes() As String
            Get
                Return ResourceManager.GetString("uxBusinessTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Стапки за пресметка.
        '''</summary>
        Friend ReadOnly Property uxCalculationItemsCaption() As String
            Get
                Return ResourceManager.GetString("uxCalculationItemsCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cities.
        '''</summary>
        Friend ReadOnly Property uxCities() As String
            Get
                Return ResourceManager.GetString("uxCities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ClosedDealsList.
        '''</summary>
        Friend ReadOnly Property uxClosedDealsList() As String
            Get
                Return ResourceManager.GetString("uxClosedDealsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colors.
        '''</summary>
        Friend ReadOnly Property uxColors() As String
            Get
                Return ResourceManager.GetString("uxColors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Communities.
        '''</summary>
        Friend ReadOnly Property uxCommunities() As String
            Get
                Return ResourceManager.GetString("uxCommunities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Фирми.
        '''</summary>
        Friend ReadOnly Property uxCompanies() As String
            Get
                Return ResourceManager.GetString("uxCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Countries.
        '''</summary>
        Friend ReadOnly Property uxCountries() As String
            Get
                Return ResourceManager.GetString("uxCountries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CustomerPivotReport.
        '''</summary>
        Friend ReadOnly Property uxCustomerPivotReport() As String
            Get
                Return ResourceManager.GetString("uxCustomerPivotReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customers.
        '''</summary>
        Friend ReadOnly Property uxCustomers() As String
            Get
                Return ResourceManager.GetString("uxCustomers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CustomerVehicleRelation.
        '''</summary>
        Friend ReadOnly Property uxCustomerVehicleRelation() As String
            Get
                Return ResourceManager.GetString("uxCustomerVehicleRelation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dashboard.
        '''</summary>
        Friend ReadOnly Property uxDashboard() As String
            Get
                Return ResourceManager.GetString("uxDashboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DDVCatalog.
        '''</summary>
        Friend ReadOnly Property uxDDVCatalog() As String
            Get
                Return ResourceManager.GetString("uxDDVCatalog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DealsList.
        '''</summary>
        Friend ReadOnly Property uxDealsList() As String
            Get
                Return ResourceManager.GetString("uxDealsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Документ бр. .
        '''</summary>
        Friend ReadOnly Property uxDocumentPayment() As String
            Get
                Return ResourceManager.GetString("uxDocumentPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentPaymentProof.
        '''</summary>
        Friend ReadOnly Property uxDocumentPaymentProof() As String
            Get
                Return ResourceManager.GetString("uxDocumentPaymentProof", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentPermisionRequest.
        '''</summary>
        Friend ReadOnly Property uxDocumentPermisionRequest() As String
            Get
                Return ResourceManager.GetString("uxDocumentPermisionRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentTehnicalExamReports.
        '''</summary>
        Friend ReadOnly Property uxDocumentTehnicalExamReports() As String
            Get
                Return ResourceManager.GetString("uxDocumentTehnicalExamReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentTehnicalExamReportsList.
        '''</summary>
        Friend ReadOnly Property uxDocumentTehnicalExamReportsList() As String
            Get
                Return ResourceManager.GetString("uxDocumentTehnicalExamReportsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentTehnicalExamReportsListIncorect.
        '''</summary>
        Friend ReadOnly Property uxDocumentTehnicalExamReportsListIncorect() As String
            Get
                Return ResourceManager.GetString("uxDocumentTehnicalExamReportsListIncorect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Statuses.
        '''</summary>
        Friend ReadOnly Property uxDocumentTehnicalExamVehiclePartsStatus() As String
            Get
                Return ResourceManager.GetString("uxDocumentTehnicalExamVehiclePartsStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentTrafficLicences.
        '''</summary>
        Friend ReadOnly Property uxDocumentTrafficLicences() As String
            Get
                Return ResourceManager.GetString("uxDocumentTrafficLicences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentTypePrint.
        '''</summary>
        Friend ReadOnly Property uxDocumentTypePrint() As String
            Get
                Return ResourceManager.GetString("uxDocumentTypePrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentTypes.
        '''</summary>
        Friend ReadOnly Property uxDocumentTypes() As String
            Get
                Return ResourceManager.GetString("uxDocumentTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocumentVehicleOwnershipProof.
        '''</summary>
        Friend ReadOnly Property uxDocumentVehicleOwnershipProof() As String
            Get
                Return ResourceManager.GetString("uxDocumentVehicleOwnershipProof", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DriveingLicenceCtegories.
        '''</summary>
        Friend ReadOnly Property uxDriveingLicenceCtegories() As String
            Get
                Return ResourceManager.GetString("uxDriveingLicenceCtegories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InternationalDriveingLicences.
        '''</summary>
        Friend ReadOnly Property uxInternationalDriveingLicences() As String
            Get
                Return ResourceManager.GetString("uxInternationalDriveingLicences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ListOfPaymentDocuments.
        '''</summary>
        Friend ReadOnly Property uxListOfPaymentDocuments() As String
            Get
                Return ResourceManager.GetString("uxListOfPaymentDocuments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OpenDealsList.
        '''</summary>
        Friend ReadOnly Property uxOpenDealsList() As String
            Get
                Return ResourceManager.GetString("uxOpenDealsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Categories.
        '''</summary>
        Friend ReadOnly Property uxPaymentCategories() As String
            Get
                Return ResourceManager.GetString("uxPaymentCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Преглед за плаќања.
        '''</summary>
        Friend ReadOnly Property uxPaymentPivotReport() As String
            Get
                Return ResourceManager.GetString("uxPaymentPivotReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PaymentTypes.
        '''</summary>
        Friend ReadOnly Property uxPaymentTypes() As String
            Get
                Return ResourceManager.GetString("uxPaymentTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PivotReportCustomerVehicle.
        '''</summary>
        Friend ReadOnly Property uxPivotReportCustomerVehicle() As String
            Get
                Return ResourceManager.GetString("uxPivotReportCustomerVehicle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PriceCatalog.
        '''</summary>
        Friend ReadOnly Property uxPriceCatalog() As String
            Get
                Return ResourceManager.GetString("uxPriceCatalog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Органи.
        '''</summary>
        Friend ReadOnly Property uxRegistrationIssuersCaption() As String
            Get
                Return ResourceManager.GetString("uxRegistrationIssuersCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RelationTypes.
        '''</summary>
        Friend ReadOnly Property uxRelationTypes() As String
            Get
                Return ResourceManager.GetString("uxRelationTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReportByPaymentCategory.
        '''</summary>
        Friend ReadOnly Property uxReportByPaymentCategory() As String
            Get
                Return ResourceManager.GetString("uxReportByPaymentCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RequestPivotReport.
        '''</summary>
        Friend ReadOnly Property uxRequestPivotReport() As String
            Get
                Return ResourceManager.GetString("uxRequestPivotReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Requests.
        '''</summary>
        Friend ReadOnly Property uxRequests() As String
            Get
                Return ResourceManager.GetString("uxRequests", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Листа на затворени барања.
        '''</summary>
        Friend ReadOnly Property uxRequestsClosed() As String
            Get
                Return ResourceManager.GetString("uxRequestsClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Листа на отворени барања.
        '''</summary>
        Friend ReadOnly Property uxRequestsOpen() As String
            Get
                Return ResourceManager.GetString("uxRequestsOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streets.
        '''</summary>
        Friend ReadOnly Property uxStreets() As String
            Get
                Return ResourceManager.GetString("uxStreets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TechnicalExamPivotReport.
        '''</summary>
        Friend ReadOnly Property uxTechnicalExamPivotReport() As String
            Get
                Return ResourceManager.GetString("uxTechnicalExamPivotReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TehnicalExamOrganizations.
        '''</summary>
        Friend ReadOnly Property uxTehnicalExamOrganizations() As String
            Get
                Return ResourceManager.GetString("uxTehnicalExamOrganizations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TehnicalExamTypes.
        '''</summary>
        Friend ReadOnly Property uxTehnicalExamTypes() As String
            Get
                Return ResourceManager.GetString("uxTehnicalExamTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TehnicalExamVehicleParts.
        '''</summary>
        Friend ReadOnly Property uxTehnicalExamVehicleParts() As String
            Get
                Return ResourceManager.GetString("uxTehnicalExamVehicleParts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TehnicalExamVehiclePartsCategories.
        '''</summary>
        Friend ReadOnly Property uxTehnicalExamVehiclePartsCategories() As String
            Get
                Return ResourceManager.GetString("uxTehnicalExamVehiclePartsCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning.
        '''</summary>
        Friend ReadOnly Property uxTwain() As String
            Get
                Return ResourceManager.GetString("uxTwain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle.
        '''</summary>
        Friend ReadOnly Property uxVehicle() As String
            Get
                Return ResourceManager.GetString("uxVehicle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleBodytypes.
        '''</summary>
        Friend ReadOnly Property uxVehicleBodytypes() As String
            Get
                Return ResourceManager.GetString("uxVehicleBodytypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleCategories.
        '''</summary>
        Friend ReadOnly Property uxVehicleCategories() As String
            Get
                Return ResourceManager.GetString("uxVehicleCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleCategoriesRelations.
        '''</summary>
        Friend ReadOnly Property uxVehicleCategoriesRelations() As String
            Get
                Return ResourceManager.GetString("uxVehicleCategoriesRelations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleCategoryForPayments.
        '''</summary>
        Friend ReadOnly Property uxVehicleCategoryForPayments() As String
            Get
                Return ResourceManager.GetString("uxVehicleCategoryForPayments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleEngineEcoProgram.
        '''</summary>
        Friend ReadOnly Property uxVehicleEngineEcoProgram() As String
            Get
                Return ResourceManager.GetString("uxVehicleEngineEcoProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleEngineMarks.
        '''</summary>
        Friend ReadOnly Property uxVehicleEngineMarks() As String
            Get
                Return ResourceManager.GetString("uxVehicleEngineMarks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleEnginePowerSourceTypes.
        '''</summary>
        Friend ReadOnly Property uxVehicleEnginePowerSourceTypes() As String
            Get
                Return ResourceManager.GetString("uxVehicleEnginePowerSourceTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleEngineTypes.
        '''</summary>
        Friend ReadOnly Property uxVehicleEngineTypes() As String
            Get
                Return ResourceManager.GetString("uxVehicleEngineTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GearBoxes.
        '''</summary>
        Friend ReadOnly Property uxVehicleGearBoxes() As String
            Get
                Return ResourceManager.GetString("uxVehicleGearBoxes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleMakers.
        '''</summary>
        Friend ReadOnly Property uxVehicleMakers() As String
            Get
                Return ResourceManager.GetString("uxVehicleMakers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleModels.
        '''</summary>
        Friend ReadOnly Property uxVehicleModels() As String
            Get
                Return ResourceManager.GetString("uxVehicleModels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehiclesList.
        '''</summary>
        Friend ReadOnly Property uxVehiclesList() As String
            Get
                Return ResourceManager.GetString("uxVehiclesList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehiclesPivotReport.
        '''</summary>
        Friend ReadOnly Property uxVehiclesPivotReport() As String
            Get
                Return ResourceManager.GetString("uxVehiclesPivotReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleSupporting.
        '''</summary>
        Friend ReadOnly Property uxVehicleSupporting() As String
            Get
                Return ResourceManager.GetString("uxVehicleSupporting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleTireTypes.
        '''</summary>
        Friend ReadOnly Property uxVehicleTireTypes() As String
            Get
                Return ResourceManager.GetString("uxVehicleTireTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleUses.
        '''</summary>
        Friend ReadOnly Property uxVehicleUses() As String
            Get
                Return ResourceManager.GetString("uxVehicleUses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some validation errors has occurred please check Broken rules collection on bottom for details.
        '''</summary>
        Friend ReadOnly Property ValidationError() As String
            Get
                Return ResourceManager.GetString("ValidationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VnrsiBRDoc.
        '''</summary>
        Friend ReadOnly Property VnrsiBRDoc() As String
            Get
                Return ResourceManager.GetString("VnrsiBRDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend ReadOnly Property Zacuvaj() As String
            Get
                Return ResourceManager.GetString("Zacuvaj", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
